### ISSUE TITLE
history - py3 artifacts

### ISSUE THREAD

**Issue by crazylazyowl** [fe7ch/cowrie#18]
Поправить вывод команды `history`. Сейчас в выводе присутствую артефакты от py3

```
root@svr04:~# history
    1  b'ls /etc'
    2  b'cat /proc/cpuinfo'
    3  b'history'
```

**Comment by crazylazyowl** [comment]
По идее здесь нужно поправить https://github.com/fe7ch/cowrie/blob/master/src/cowrie/commands/base.py#L968

**Comment by crazylazyowl** [comment]
По идее этого должно хватить `                self.write(f" {count:4d}  {line.decode()}\n")`

**Comment by gglchrm** [comment]
Этого хватило
